# Generated by Django 2.0.2 on 2018-03-02 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('field_type', models.CharField(choices=[('TXT', 'Text'), ('TXB', 'Textbox'), ('CHK', 'Checkbox'), ('RDO', 'Radio')], max_length=100, verbose_name='field types')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'dynamic attributes',
            },
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'dynamic forms',
            },
        ),
        migrations.CreateModel(
            name='ValueAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(blank=True, max_length=256, null=True, verbose_name='value')),
                ('dynamic_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicAttribute', verbose_name='attribute')),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicForm', verbose_name='form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='attribute',
            field=models.ManyToManyField(through='django_dynamic_forms.ValueAttribute', to='django_dynamic_forms.DynamicAttribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicForm', verbose_name='parent'),
        ),
    ]
