# Generated by Django 2.0.2 on 2018-03-06 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicOptionSelects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'dynamic option select',
            },
        ),
        migrations.CreateModel(
            name='FormAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('css_class', models.CharField(blank=True, max_length=256, null=True, verbose_name='css class')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleOptionSelects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'simple option select',
            },
        ),
        migrations.RemoveField(
            model_name='valueattribute',
            name='dynamic_attribute',
        ),
        migrations.RemoveField(
            model_name='valueattribute',
            name='dynamic_form',
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='code',
            field=models.CharField(default=None, max_length=256, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='css_class',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='css class'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='is_wizard',
            field=models.BooleanField(default=False, verbose_name='is wizard?'),
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='field_type',
            field=models.CharField(choices=[('TXT', 'Text'), ('TXB', 'Textarea'), ('CHK', 'Checkbox'), ('RDO', 'Radio'), ('SLT', 'Select')], max_length=100, verbose_name='field types'),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='attribute',
            field=models.ManyToManyField(through='django_dynamic_forms.FormAttribute', to='django_dynamic_forms.DynamicAttribute', verbose_name='attribute'),
        ),
        migrations.DeleteModel(
            name='ValueAttribute',
        ),
        migrations.AddField(
            model_name='formattribute',
            name='dynamic_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicAttribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='formattribute',
            name='dynamic_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicForm', verbose_name='form'),
        ),
        migrations.AddField(
            model_name='dynamicoptionselects',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicAttribute', verbose_name='parent'),
        ),
    ]
