# Generated by Django 2.0.3 on 2018-03-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('django_dynamic_forms', '0004_auto_20180319_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name': 'list name',
                'verbose_name_plural': 'list names',
            },
        ),
        migrations.CreateModel(
            name='ListOptionSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='groups')),
                ('list_name', models.ManyToManyField(to='django_dynamic_forms.ListName', verbose_name='lists name')),
            ],
            options={
                'verbose_name': 'list option select',
                'verbose_name_plural': 'lists option select',
            },
        ),
        migrations.AlterModelOptions(
            name='dynamicform',
            options={'verbose_name': 'dynamic form', 'verbose_name_plural': 'dynamic forms'},
        ),
        migrations.RemoveField(
            model_name='formattribute',
            name='css_class',
        ),
        migrations.AddField(
            model_name='formattribute',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='id_element',
            field=models.CharField(help_text='Value for HTML attribute (id="example").', max_length=256, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='listname',
            name='select_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicAttribute', verbose_name='select list'),
        ),
    ]
