# Generated by Django 2.0.2 on 2018-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0005_auto_20180327_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicattribute',
            name='id_element',
            field=models.CharField(blank=True, help_text='Value for HTML attribute (id="example").', max_length=256, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, to='django_dynamic_forms.DynamicParameter', verbose_name='parameters'),
        ),
    ]
