# Generated by Django 2.0.2 on 2018-04-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0006_auto_20180402_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formattribute',
            old_name='dynamic_attribute',
            new_name='dynamic_element',
        ),
    ]
