# Generated by Django 2.0.2 on 2018-04-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0006_auto_20180402_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formattribute',
            name='dynamic_attribute',
        ),
        migrations.AddField(
            model_name='formattribute',
            name='dynamic_element',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.DynamicAttribute', verbose_name='element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='element_type',
            field=models.CharField(choices=[('input', 'input'), ('textarea', 'textarea'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('select', 'select'), ('div', 'div'), ('label', 'label'), ('button', 'button'), ('span', 'span'), ('switch', 'switch'), ('hr', 'hr'), ('i', 'i'), ('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6')], max_length=100, verbose_name='element type'),
        ),
    ]
