# Generated by Django 2.0.2 on 2018-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0008_auto_20180404_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicattribute',
            name='element_type',
            field=models.CharField(choices=[('input', 'input'), ('textarea', 'textarea'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('select', 'select'), ('div', 'div'), ('label', 'label'), ('button', 'button'), ('span', 'span'), ('switch', 'switch'), ('ngb-accordion', 'ngb-accordion'), ('ngb-panel', 'ngb-panel'), ('ng-template', 'ng-template'), ('hr', 'hr'), ('i', 'i'), ('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6')], max_length=100, verbose_name='element type'),
        ),
    ]
