# Generated by Django 2.0.2 on 2018-05-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0012_auto_20180503_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicattribute',
            name='order',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='order',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='formattribute',
            name='order',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='order'),
        ),
    ]
