# Generated by Django 2.0.2 on 2018-05-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0013_auto_20180514_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
            ],
            options={
                'verbose_name': 'report detail',
                'verbose_name_plural': 'report detail',
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='order')),
                ('elements', models.ManyToManyField(to='django_dynamic_forms.DynamicAttribute', verbose_name='elements')),
                ('report_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_forms.ReportDetail', verbose_name='report detail')),
            ],
            options={
                'verbose_name': 'report section',
                'verbose_name_plural': 'report section',
            },
        ),
    ]
