# Generated by Django 2.0.2 on 2018-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0014_reportdetail_reportsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicattribute',
            name='tag_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='tag name'),
        ),
    ]
