# Generated by Django 2.0.7 on 2018-07-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_forms', '0015_dynamicattribute_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicattribute',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='django_dynamic_forms.DynamicParameter', verbose_name='parameters'),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='django_dynamic_forms.DynamicParameter', verbose_name='parameters'),
        ),
    ]
